services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_local_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Pass10
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql-data:
